require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/schema.rb"

Style/StringLiterals:
  Exclude:
    - "db/schema.rb"

Metrics/AbcSize:
  Max: 20

RSpec/NestedGroups:
  Max: 4
