default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: twitter_dm_development

test:
  <<: *default
  database: twitter_dm_test

production:
  <<: *default
  database: twitter_dm_production
  username: <%= ENV.fetch("MYAPP_DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("MYAPP_DATABASE_PASSWORD", "password") %>
